### ISSUE TITLE
Tests failing on Ember-Cli 2.6.2

### ISSUE THREAD

**Issue by atremblay-seniorlink** [dgeb/ember-blog-engine#2]
When pulling down a fresh copy of the repo and running tests I get two failures:
```
not ok 16 PhantomJS 2.1 - Integration | Component | date picker: it renders
      Assertion Failed: A helper named 'date-picker' could not be found

not ok 26 PhantomJS 2.1 - Unit | Route | post: it exists
      Promise rejected before it exists: Attempting to register an unknown factory: `route:post`

1..27
# tests 27
# pass  25
# skip  0
# fail  2
```
Other messages:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-data`
    at Function.Addon.lookup (/../ember-engines/ember-blog-engine/node_modules/ember-cli/lib/models/addon.js:896:27)
```
## Versions 
**os:** darwin x64
**node:** 5.6.0
**npm:** 3.6.0
**ember-cli:** 2.6.2
**bower:** 1.7.7

## Repro steps: 
$ clone repo
$ npm install
$ bower install
$ ember test

Wondering if I have an incompatible version or if there's a missing setup step.

**Comment by dgeb** [comment]
I've just upgraded this repo to the latest ember, ember-cli, and ember-engines. Tests are now all passing (but are inadequate now tbh).

Please open a fresh issue if you have any further problems.
