### ISSUE TITLE
Upgrade this to latest ember-engines version

### ISSUE THREAD

**Issue by Duder-onomy** [dgeb/ember-blog-engine#3]
Hi @dgeb Thanks for working hard on engines. 

We are trying to implement engines in our application, but we are hitting walls left and right with outdated documentation / stale github issues / confusing error messages / diff error messaging during npm link and direct install. 

Would you be able to update this repo to the latest ember-engines version?  The source of truth for how to implement an engine should really just be this source code and not the docs until this is not marked as experimental anymore.

If you don't have the time to update this repo to the latest engines, can you point me towards a modern engines implementation using the latest version of ember?

**Comment by dgeb** [comment]
I've just upgraded this repo to the latest ember, ember-cli, and ember-engines.

**Comment by dgeb** [comment]
The https://github.com/dgeb/ember-engines-demo repo was also upgraded to the latest versions of everything, so hopefully these repos are back to being good simple examples.

**Comment by Duder-onomy** [comment]
RAWK! Thanks so much. 
It is tough looking for resources on Engines right now, it seems like most of the people using them are working on closed source projects. 
Having this repo updated and working is super helpful to me and others. Thanks!

**Comment by dgeb** [comment]
Glad to help, @Duder-onomy :)

By the way, the ember-engines guides are another open source example. That project uses in-repo engines that are lazy loaded: https://github.com/ember-engines/ember-engines.com

**Comment by Duder-onomy** [comment]
Oh Gangster! Thanks! I didn't know that, we were struggling with the lazy loading part. Hopefully people will find this thread and look there for inspiration!
